<?php

use App\Filament\Resources\LensTypes\Pages\CreateLensType;
use App\Filament\Resources\LensTypes\Pages\ListLensTypes;
use App\Filament\Resources\Products\Pages\CreateProduct;
use App\Filament\Resources\Products\Pages\EditProduct;
use App\Filament\Resources\Products\Pages\ListProducts;
use App\Models\Brand;
use App\Models\LensType;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\ProductVariant;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Storage;
use Livewire\Livewire;

uses(RefreshDatabase::class);

test('staff and admin users can list products', function (string $factoryState) {
    $user = User::factory()->{$factoryState}()->create();
    $products = Product::factory()->count(2)->create();

    $this->actingAs($user);

    Livewire::test(ListProducts::class)
        ->assertCanSeeTableRecords($products);
})->with([
    'admin' => ['admin'],
    'staff' => ['staff'],
]);

test('staff can create and edit products with variants', function () {
    $staff = User::factory()->staff()->create();
    $brand = Brand::factory()->create();
    $category = ProductCategory::factory()->create();

    $this->actingAs($staff);

    Livewire::test(CreateProduct::class)
        ->fillForm([
            'brand_id' => $brand->id,
            'category_id' => $category->id,
            'name' => 'Aviator Frame',
            'slug' => 'aviator-frame',
            'is_active' => true,
            'variants' => [
                [
                    'name' => 'Silver',
                    'sku' => 'AVF-SLV-001',
                    'price' => 189.99,
                    'stock_quantity' => 4,
                    'low_stock_threshold' => 5,
                    'is_active' => true,
                    'ar_eligible' => true,
                    'ar_asset_reference' => 'frames/aviator-silver.glb',
                ],
            ],
        ])
        ->call('create')
        ->assertNotified()
        ->assertHasNoFormErrors();

    $product = Product::query()->where('slug', 'aviator-frame')->first();

    expect($product)->not->toBeNull()
        ->and($product->variants)->toHaveCount(1);

    Livewire::test(EditProduct::class, ['record' => $product->getRouteKey()])
        ->fillForm([
            'name' => 'Aviator Frame Updated',
        ])
        ->call('save')
        ->assertNotified()
        ->assertHasNoFormErrors();

    expect($product->fresh()->name)->toBe('Aviator Frame Updated');
});

test('product table shows total variant quantity', function () {
    $staff = User::factory()->staff()->create();

    $product = Product::factory()->create(['name' => 'Frame With Stock']);
    ProductVariant::factory()->for($product)->create(['stock_quantity' => 5]);
    ProductVariant::factory()->for($product)->create(['stock_quantity' => 8]);

    $this->actingAs($staff);

    Livewire::test(ListProducts::class)
        ->assertTableColumnStateSet('total_quantity', 13, $product);
});

test('admin can create lens types', function () {
    $admin = User::factory()->admin()->create();

    $this->actingAs($admin);

    Livewire::test(CreateLensType::class)
        ->fillForm([
            'name' => 'photochromic',
            'description' => 'Light-responsive lenses.',
        ])
        ->call('create')
        ->assertNotified()
        ->assertHasNoFormErrors();

    $this->assertDatabaseHas(LensType::class, [
        'name' => 'photochromic',
    ]);

    Livewire::test(ListLensTypes::class)
        ->assertCanSeeTableRecords(LensType::query()->where('name', 'photochromic')->get());
});

test('product edit page loads without error', function () {
    $staff = User::factory()->staff()->create();
    $product = Product::factory()->create();

    $this->actingAs($staff);

    Livewire::test(EditProduct::class, ['record' => $product->getRouteKey()])
        ->assertSuccessful()
        ->assertHasNoFormErrors();
});

test('products table image column returns accessible url for stored image path', function () {
    $staff = User::factory()->staff()->create();
    Storage::fake('public');

    $product = Product::factory()->create([
        'images' => ['products/test-frame.jpg'],
    ]);

    Storage::disk('public')->put('products/test-frame.jpg', 'fake-image');

    $this->actingAs($staff);

    // The image URL generated by Storage::disk should be a full URL
    $url = Storage::disk('public')->url('products/test-frame.jpg');
    expect($url)->toContain('products/test-frame.jpg');

    // The API should return the full URL for images, not raw paths
    $customer = User::factory()->customer()->create();
    $this->actingAs($customer, 'sanctum')
        ->getJson("/api/products/{$product->id}")
        ->assertSuccessful()
        ->assertJsonPath('data.images.0', 'products/test-frame.jpg'); // raw path — Android builds URL
});
